#!/bin/bash
#
# - Set up a new Laravel project
# - Create a new MySQL/MariaDB database
# - Set up project config (in .env)
# - Optionally set up Apache vHost directive
# - Optionally set up a new project GitHub repo
# - Optionally sets up node modules for the project
#
# Requires [Composer](https://getcomposer.org/), which should be referenced in your $PATH
# Requires Laravel installer to be installed globally (`composer global require "laravel/installer"`)
# ------------------------------------------------------------------------------

# Include dependencies for this script.
# ------------------------------------------------------------------------------
THIS=$(readlink -f ${BASH_SOURCE[0]})
PROJECT_ROOT=$(dirname $THIS)
for FILENAME in $PROJECT_ROOT/src/*; do
    if [[ -f ${FILENAME} ]] ; then
        . "${FILENAME}"
    fi
done

function options {
    read -p "Do you want to set up and install an Apache virtual hosts directive? [y/N]" yn
    case $yn in
        [Yy]* )
        generate_apache_vhost $SITE_NAME
        activate_apache_vhost $SITE_NAME
        ;;
        [Nn]* ) echo "No Apache VHost setup."
        ;;
        * ) echo "Please answer yes or no.";;
    esac

    read -p "Do you want to install node modules? [y/N]" yn
    case $yn in
        [Yy]* ) install_node_modules;;
        [Nn]* ) echo "No node modules install.";;
        * ) echo "Please answer yes or no.";;
    esac

    read -p "Set up a new GitHub repo for this project? [y/N]" yn
    case $yn in
        [Yy]* ) setup_github_repo;;
        [Nn]* ) ;;
        * ) echo "Please answer yes or no.";;
    esac
}

# Trigger the required functions in the correct order.
# ------------------------------------------------------------------------------
environment_and_path
setup_laravel
generate_mysql_database
generate_dotenv $ROOT_PATH
options
