#!/bin/bash
# Set up a GitHub Repo
# ------------------------------------------------------------------------------
function setup_github_repo {
    cd $ROOT_PATH

    # remove existing git repo
    #sudo rm -rf $ROOT_PATH/.git
    git init
    repo_name=$1
    dir_name=`basename $(pwd)`
    invalid_credentials=0

    if [ "$repo_name" = "" ]; then
        echo "  Repo name (hit enter to use '$dir_name')?"
        read repo_name
    fi

    if [ "$repo_name" = "" ]; then
        repo_name=$dir_name
    fi

    GIT_USERNAME=`git config github.user`
    if [ "$GIT_USERNAME" = "" ]; then
        echo "  Could not find Git username, run 'git config --global github.user <username>'"
        invalid_credentials=1
    fi

    token=`git config github.token`
    if [ "$token" = "" ]; then
        echo "  Could not find token, run 'git config --global github.token <token>'"
        invalid_credentials=1
    fi

    if [ "$invalid_credentials" -eq "1" ]; then
        return 1
    fi

    echo -n "  Creating Github repository '$repo_name' ..."
    curl -u "$GIT_USERNAME:$token" https://api.github.com/user/repos -d '{"name":"'$repo_name'"}' > /dev/null 2>&1
    echo " done."

    echo -n "  Pushing local code to remote ..."
    git remote add origin git@github.com:$GIT_USERNAME/$repo_name.git > /dev/null 2>&1
    git push -u origin master > /dev/null 2>&1
    git add -A
    git commit -m "First Commit"
    git push origin master
    echo " done."

}
